name: Package Docker Image

on:
  push:
    branches: 
      - "*"
    paths:
      - "**"
      - "!images/**"
      - "!**.png"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Get branch name
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: get_branch

    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
      shell: bash

    - name: Get version tag
      run: echo "##[set-output name=version;]$(echo `git ls-remote https://${{ secrets.my_pat }}@github.com/atlanhq/${REPOSITORY_NAME}.git ${{ steps.get_branch.outputs.branch }} | awk '{ print $1}' | cut -c1-7`)abcd"
      id: get_version

    - name: Create images
      run: |
         docker build --build-arg ACCESS_TOKEN_USR=$GITHUB_ACTOR --build-arg ACCESS_TOKEN_PWD=${{ secrets.my_pat }} -t docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}-${{ steps.get_branch.outputs.branch }}:latest .
         docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}-${{ steps.get_branch.outputs.branch }}:latest docker.pkg.github.com/$GITHUB_REPOSITORY/${REPOSITORY_NAME}-${{ steps.get_branch.outputs.branch }}:${{ steps.get_version.outputs.version }}
         docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.my_pat }}
         docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${REPOSITORY_NAME}-${{ steps.get_branch.outputs.branch }}:latest
         docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${REPOSITORY_NAME}-${{ steps.get_branch.outputs.branch }}:${{ steps.get_version.outputs.version }}
    # Send a slack notification message on the specified channel with the failure github actions workflow report.
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      if: failure()
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://cdn3.iconfinder.com/data/icons/popular-services-brands/512/github-512.png
        SLACK_MESSAGE: "- @infra, Job ${{ job.status }} :rocket:"
        SLACK_TITLE: Message
        SLACK_USERNAME: Github-Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
